# Generated by Django 5.1.5 on 2025-02-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
