# Generated by Django 5.1.5 on 2025-02-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_anime_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
